### PR TITLE
Allow the creation of Sites with Builder

### PR DESCRIPTION
**Pull request by BobWez98**
This PR does a few things.

* Solves #25 
* Drops the support for Statamic 4, because it's using Statamic 5 functionality in the registering of the sites
* Removes composer.lock so projects can figure out what versions match
* Ran pint

### CODE REVIEW

**Comment by tdwesten** [comment]
Hi @BobWez98,

Thank you for adding this! I tested it locally, and it works as expected. If you include the warning about clearing the cache, it will be ready to merge.

🙏

**Comment by tdwesten** [comment]
Hmm, near the "How to Create a Site" instructions :)

**Comment by BobWez98** [comment]
Like so?

**Comment by tdwesten** [comment]
Yeah super!

**Pull request merged**
